<a href="https://colab.research.google.com/github/AshilPrasad/Machine-learning/blob/main/imdb_movies_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/imdb_movie_data.csv")
df

movie    year certificate    genre.1     genre.2  \
0        Aguirre, der Zorn Gottes  (1972)          '-     Action   Adventure   
1                     The General  (1926)          '-     Action   Adventure   
2    Kakushi-toride no san-akunin  (1958)          '-     Action   Adventure   
3           The Magnificent Seven  (1960)          '-     Action   Adventure   
4                    Sherlock Jr.  (1924)          '-     Action      Comedy   
..                            ...     ...         ...        ...         ...   
995                       Memento  (2000)          UA    Mystery    Thriller   
996        The Outlaw Josey Wales  (1976)          UA    Western          '-   
997                  Sardar Udham  (2021)      UA 13+  Biography       Crime   
998                Thirteen Lives  (2022)      UA 16+     Action   Adventure   
999                Dil Chahta Hai  (2001)     Unrated     Comedy       Drama   

        genre.3  imdb_rating metascore time_minute     vote gross_earning  
0     Biography          7.8        '-      95 min    58519            '-  
1        Comedy          8.1        '-      67 min    92992        $1.03M  
2         Drama          8.1        89     139 min    40060            '-  
3         Drama          7.7        74     128 min    97247        $4.91M  
4       Romance          8.2        '-      45 min    51515        $0.98M  
..          ...          ...       ...         ...      ...           ...  
995          '-          8.4        81     113 min  1252090       $25.54M  
996          '-          7.8        69     135 min    75658       $31.80M  
997       Drama          8.4        '-     164 min    43555            '-  
998   Biography          7.8        66     147 min    58273            '-  
999     Romance          8.1        '-     183 min    73359        $0.30M  

[1000 rows x 11 columns]

In [ ]:
df.head()

movie    year certificate genre.1     genre.2  \
0      Aguirre, der Zorn Gottes  (1972)          '-  Action   Adventure   
1                   The General  (1926)          '-  Action   Adventure   
2  Kakushi-toride no san-akunin  (1958)          '-  Action   Adventure   
3         The Magnificent Seven  (1960)          '-  Action   Adventure   
4                  Sherlock Jr.  (1924)          '-  Action      Comedy   

      genre.3  imdb_rating metascore time_minute   vote gross_earning  
0   Biography          7.8        '-      95 min  58519            '-  
1      Comedy          8.1        '-      67 min  92992        $1.03M  
2       Drama          8.1        89     139 min  40060            '-  
3       Drama          7.7        74     128 min  97247        $4.91M  
4     Romance          8.2        '-      45 min  51515        $0.98M

In [ ]:
df.tail()

movie    year certificate    genre.1     genre.2  \
995                 Memento  (2000)          UA    Mystery    Thriller   
996  The Outlaw Josey Wales  (1976)          UA    Western          '-   
997            Sardar Udham  (2021)      UA 13+  Biography       Crime   
998          Thirteen Lives  (2022)      UA 16+     Action   Adventure   
999          Dil Chahta Hai  (2001)     Unrated     Comedy       Drama   

        genre.3  imdb_rating metascore time_minute     vote gross_earning  
995          '-          8.4        81     113 min  1252090       $25.54M  
996          '-          7.8        69     135 min    75658       $31.80M  
997       Drama          8.4        '-     164 min    43555            '-  
998   Biography          7.8        66     147 min    58273            '-  
999     Romance          8.1        '-     183 min    73359        $0.30M

In [ ]:
df.describe()

imdb_rating          vote
count  1000.000000  1.000000e+03
mean      7.967800  3.122232e+05
std       0.275679  3.781816e+05
min       7.600000  2.573000e+04
25%       7.800000  6.095775e+04
50%       7.900000  1.535870e+05
75%       8.100000  4.327572e+05
max       9.300000  2.714258e+06

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   movie          1000 non-null   object 
 1   year           1000 non-null   object 
 2   certificate    1000 non-null   object 
 3   genre.1        1000 non-null   object 
 4   genre.2        1000 non-null   object 
 5   genre.3        1000 non-null   object 
 6   imdb_rating    1000 non-null   float64
 7   metascore      1000 non-null   object 
 8   time_minute    1000 non-null   object 
 9   vote           1000 non-null   int64  
 10  gross_earning  1000 non-null   object 
dtypes: float64(1), int64(1), object(9)
memory usage: 86.1+ KB


In [ ]:
df.isna().sum()

movie            0
year             0
certificate      0
genre.1          0
genre.2          0
genre.3          0
imdb_rating      0
metascore        0
time_minute      0
vote             0
gross_earning    0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["movie"]=le.fit_transform(df["movie"])
df["year"]=le.fit_transform(df["year"])
df["certificate"]=le.fit_transform(df["certificate"])
df["genre.1"]=le.fit_transform(df["genre.1"])
df["genre.2"]=le.fit_transform(df["genre.2"])
df["genre.3"]=le.fit_transform(df["genre.3"])
df["metascore"]=le.fit_transform(df["metascore"])
df["time_minute"]=le.fit_transform(df["time_minute"])
df["gross_earning"]=le.fit_transform(df["gross_earning"])
df

movie  year  certificate  genre.1  genre.2  genre.3  imdb_rating  \
0       33    50            0        0        1        1          7.8   
1      788     5            0        0        1        2          8.1   
2      398    36            0        0        1        4          8.1   
3      839    38            0        0        1        4          7.7   
4      665     3            0        0        3       13          8.2   
..     ...   ...          ...      ...      ...      ...          ...   
995    504    78           17       11       17       19          8.4   
996    856    54           17       13       20       19          7.8   
997    644    99           18        3        4        4          8.4   
998    902   100           19        0        1        1          7.8   
999    212    79           20        4        5       13          8.1   

     metascore  time_minute     vote  gross_earning  
0            0          139    58519            738  
1            0          114    92992             88  
2           51           39    40060            738  
3           36           28    97247            515  
4            0          111    51515             84  
..         ...          ...      ...            ...  
995         43           13  1252090            373  
996         31           35    75658            436  
997          0           64    43555            738  
998         28           47    58273            738  
999          0           82    73359             53  

[1000 rows x 11 columns]

In [ ]:
x=df.iloc[:,:-1].values
x

array([[3.3000e+01, 5.0000e+01, 0.0000e+00, ..., 0.0000e+00, 1.3900e+02,
        5.8519e+04],
       [7.8800e+02, 5.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.1400e+02,
        9.2992e+04],
       [3.9800e+02, 3.6000e+01, 0.0000e+00, ..., 5.1000e+01, 3.9000e+01,
        4.0060e+04],
       ...,
       [6.4400e+02, 9.9000e+01, 1.8000e+01, ..., 0.0000e+00, 6.4000e+01,
        4.3555e+04],
       [9.0200e+02, 1.0000e+02, 1.9000e+01, ..., 2.8000e+01, 4.7000e+01,
        5.8273e+04],
       [2.1200e+02, 7.9000e+01, 2.0000e+01, ..., 0.0000e+00, 8.2000e+01,
        7.3359e+04]])

In [ ]:
y=df.iloc[:,-1].values
y

array([738,  88, 738, 515,  84,  28, 738, 738, 738, 738, 738,  38,  23,
       738, 738, 738, 571, 738, 738, 561, 121, 738,  44, 738, 738, 738,
        30,  38, 738,  46, 154, 314, 537,  51, 105, 738, 738, 738, 738,
       738,  66, 117, 266, 426, 518, 615, 306, 571, 738,  43, 738, 738,
       738,  42,  46,  53, 125, 511, 548, 738, 738,  52, 738, 513, 302,
       738, 738, 504,  15, 738,  32, 738, 738, 738, 738, 577,  93, 738,
        26,  47, 738,  34,  39,  41,  58, 563, 290, 636, 738,  31, 738,
       738, 738, 738, 738, 738,  29,  29,  30,  33,  34,  35,  35,  43,
        51,  54,  62,  74,  75,  96, 311,  18, 738, 120, 738,  53,  24,
       423, 723, 738, 504, 504, 738,  33, 738,  68, 738, 504,  44, 131,
        31,  39, 738, 738,  37,  38,  45,  64,  95, 189, 303, 357, 428,
        99, 738,  20, 738,  34,  36,  41,  43, 738, 173, 738, 738, 738,
       738, 738, 498, 140,   0, 738, 448, 687, 738, 734, 310, 261, 738,
       659, 738, 225, 738, 738, 573, 258, 738, 738, 579, 465, 41

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[5.70000e+01, 7.20000e+01, 1.50000e+01, ..., 0.00000e+00,
        6.00000e+01, 5.39780e+04],
       [6.78000e+02, 9.40000e+01, 1.30000e+01, ..., 4.10000e+01,
        6.00000e+00, 9.64550e+04],
       [4.70000e+02, 8.00000e+01, 1.40000e+01, ..., 4.40000e+01,
        9.00000e+00, 4.67680e+04],
       ...,
       [8.25000e+02, 8.10000e+01, 1.70000e+01, ..., 1.70000e+01,
        5.40000e+01, 4.48274e+05],
       [5.87000e+02, 8.50000e+01, 1.30000e+01, ..., 5.20000e+01,
        1.40000e+02, 9.63950e+04],
       [9.35000e+02, 3.00000e+01, 0.00000e+00, ..., 5.40000e+01,
        1.33000e+02, 2.65740e+04]])

In [ ]:
x_test

array([[5.02000e+02, 8.30000e+01, 1.40000e+01, ..., 3.40000e+01,
        2.40000e+01, 2.21142e+05],
       [9.74000e+02, 1.13000e+02, 1.50000e+01, ..., 2.80000e+01,
        1.30000e+01, 1.68346e+05],
       [2.62000e+02, 4.90000e+01, 1.50000e+01, ..., 2.90000e+01,
        8.10000e+01, 4.49170e+04],
       ...,
       [3.06000e+02, 1.00000e+02, 1.20000e+01, ..., 4.10000e+01,
        1.70000e+01, 8.81010e+04],
       [6.48000e+02, 1.00000e+01, 0.00000e+00, ..., 4.90000e+01,
        1.37000e+02, 2.88110e+04],
       [1.90000e+02, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.21000e+02, 6.58400e+04]])

In [ ]:
y_train

array([738, 414,  44, 738, 284,  14, 738, 273, 206, 654, 556, 483, 535,
       191, 226, 451,  72, 337, 264, 368,  47,  36,  69,  62,  87, 291,
       370, 638,  19, 738, 399, 605,  34,  10, 738, 726, 368, 738, 194,
       450, 409, 182, 738,  68, 304,  33,  21, 736, 738,  74, 717, 280,
        40, 738, 204,  39, 622, 738, 688, 738, 424, 486,  38,  90, 738,
       738, 401, 366,  25, 637, 659, 128, 303, 738, 738, 124, 738, 738,
       376, 685, 484,  20,  61, 211, 218, 549, 363, 738, 208, 485, 738,
       117,  59,  75, 330, 125, 252, 418, 631, 738, 738,  79, 171, 434,
       472, 119,  81, 159, 738, 285, 561, 738, 725, 686, 652,   1, 738,
       657, 738, 107, 738,  38, 250, 168, 372, 407,  41,  52, 562, 738,
       581, 186, 738, 477, 738,  23, 680,  31, 738, 406, 499, 660, 585,
       591,  50, 455,  54, 738, 594, 411, 263, 543, 210, 687, 738,  76,
       494, 118, 286, 567, 738, 120, 738, 648, 560,  51, 738, 309, 695,
       738,  40, 738, 127,  31, 113, 382, 113,  43, 282, 388, 36

In [ ]:
y_test

array([351, 203, 705, 339, 738,  67, 346, 721, 738,  45, 601,  93, 683,
       294,  56, 369,  29, 566, 362, 199,   4, 573, 675, 738, 227, 262,
        35, 624, 257, 270, 517, 189, 534, 185, 578, 271, 516, 738,   5,
       738, 633,  29, 611, 559, 620, 546, 627, 224, 738, 738,  64, 325,
       462, 367, 738, 154, 463, 738, 305, 134, 529,  46, 272, 356, 278,
        82, 397, 277,  32, 300,  74, 341, 345,  94, 234,  55, 588, 738,
       334, 133, 232, 738, 528, 504, 141, 738, 738, 501,  97, 724, 598,
       101,  41, 200, 337,  52, 738, 738, 513, 380, 699, 738, 738, 468,
       108,  45, 267, 555, 738, 126, 619, 350, 393, 433, 290,  83, 738,
       178, 188, 293, 555, 576, 504, 254, 319, 643, 617, 295, 435, 490,
       175, 321, 735, 373, 438,  53, 504, 656, 738, 738, 518, 628,  12,
       142,  63, 251, 464, 621, 229, 233, 689, 498, 702, 446, 214, 312,
       353, 269, 738, 359,  85, 148, 241, 289, 109, 111, 569, 733, 649,
       461, 482, 497, 311, 299,  37, 329, 242, 551, 738, 694, 38

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
x_train

array([[-1.54577094,  0.0950799 ,  0.68253816, ..., -1.79513502,
         0.20231588, -0.6880246 ],
       [ 0.64788207,  0.96872571,  0.34464798, ...,  0.39526399,
        -0.96453494, -0.5754537 ],
       [-0.08686805,  0.41276928,  0.51359307, ...,  0.55553709,
        -0.89970989, -0.70713226],
       ...,
       [ 1.16715259,  0.45248046,  1.02042834, ..., -0.8869208 ,
         0.07266579,  0.35692335],
       [ 0.32642889,  0.61132515,  0.34464798, ...,  0.98293202,
         1.93098376, -0.57561271],
       [ 1.55572237, -1.57278939, -1.85163819, ...,  1.08978075,
         1.77972532, -0.76064962]])

In [ ]:
x_test

array([[-0.00891618,  0.47104738,  0.5037673 , ...,  0.01609018,
        -0.53754175, -0.23157359],
       [ 1.57518779,  1.71683828,  0.67376752, ..., -0.3130272 ,
        -0.79266727, -0.37069296],
       [-0.81439277, -0.94084897,  0.67376752, ..., -0.2581743 ,
         0.78447233, -0.69593283],
       ...,
       [-0.66672206,  1.17699556,  0.16376687, ...,  0.40006047,
        -0.69989436, -0.58214143],
       [ 0.48108208, -2.56037714, -1.8762357 , ...,  0.83888365,
         2.08329318, -0.73837273],
       [-1.05603575, -2.97564077, -1.8762357 , ..., -1.84890833,
         1.71220151, -0.64079997]])

In [ ]:
#model creation
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
KNN_model=KNeighborsClassifier()
NBA_model=MultinomialNB()
SVMA_model=SVC()
lis=[KNN_model,NBA_model,SVMA_model]





In [ ]:
for i in lis:
  print(i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print(y_pred)
  print("accuracy score:",accuracy_score(y_test,y_pred))
  print("classification_report:",classification_report(y_test,y_pred))
print()


KNeighborsClassifier()
[170  60  49 124  10 139 282  35 738 738 738 738  79 265  59 355 738  76
  14 180   9  39 473  10  34  31  38  43 231 256 738  33 230  59  35 386
 738 401   1 738  29 738  28 256 159  45  44 237  79 738 138  40 301 179
 738 738 209 738  94 164 109 738 738 347 230  59 139 179 738 372  33  28
 237  57 155 738  44 738 324 174 168 738 205 738 593  19 211  57 738 280
  71 255  59 372  59  54   7 738 738 164   1  97  74  40 195 130 149  49
 410 324  43 372 192 434 738  35  44 256   9  44  43  28  22 166 159 301
 153  38 183 322  80 275 202 182 404 738 738 422 738  30 117  51  64 354
  80 180 404 231 349 738  34 738  34  76 181  40 186   1  44 164 102 255
 427  44 238  53  35 250 228  28 210  65  30  49  28 210 614 122 738 128
  44  59 738 244 738 738 202 137 113  35 255 244 168  40 486   1  51  29
  94  30 738 372  97  94 149  40  44 179  49 349  33  20  81 275  10 137
  45  45 166  14 738 256  58  38  80 738 738  33  79 231  71 738 128   9
 738 738 205 143  71 738 738

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1

ValueError: ignored