<a href="https://colab.research.google.com/github/AshilPrasad/Machine-learning/blob/main/salarys(svm%2Cknn%2Cnaive_bayes).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/ds_salaries.csv')
df

work_year experience_level employment_type                 job_title  \
0          2023               SE              FT  Principal Data Scientist   
1          2023               MI              CT               ML Engineer   
2          2023               MI              CT               ML Engineer   
3          2023               SE              FT            Data Scientist   
4          2023               SE              FT            Data Scientist   
...         ...              ...             ...                       ...   
3750       2020               SE              FT            Data Scientist   
3751       2021               MI              FT  Principal Data Scientist   
3752       2020               EN              FT            Data Scientist   
3753       2020               EN              CT     Business Data Analyst   
3754       2021               SE              FT      Data Science Manager   

       salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0       80000             EUR          85847                 ES           100   
1       30000             USD          30000                 US           100   
2       25500             USD          25500                 US           100   
3      175000             USD         175000                 CA           100   
4      120000             USD         120000                 CA           100   
...       ...             ...            ...                ...           ...   
3750   412000             USD         412000                 US           100   
3751   151000             USD         151000                 US           100   
3752   105000             USD         105000                 US           100   
3753   100000             USD         100000                 US           100   
3754  7000000             INR          94665                 IN            50   

     company_location company_size  
0                  ES            L  
1                  US            S  
2                  US            S  
3                  CA            M  
4                  CA            M  
...               ...          ...  
3750               US            L  
3751               US            L  
3752               US            S  
3753               US            L  
3754               IN            L  

[3755 rows x 11 columns]

In [ ]:
df.head()

work_year experience_level employment_type                 job_title  \
0       2023               SE              FT  Principal Data Scientist   
1       2023               MI              CT               ML Engineer   
2       2023               MI              CT               ML Engineer   
3       2023               SE              FT            Data Scientist   
4       2023               SE              FT            Data Scientist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0   80000             EUR          85847                 ES           100   
1   30000             USD          30000                 US           100   
2   25500             USD          25500                 US           100   
3  175000             USD         175000                 CA           100   
4  120000             USD         120000                 CA           100   

  company_location company_size  
0               ES            L  
1               US            S  
2               US            S  
3               CA            M  
4               CA            M

In [ ]:
df.tail()

work_year experience_level employment_type                 job_title  \
3750       2020               SE              FT            Data Scientist   
3751       2021               MI              FT  Principal Data Scientist   
3752       2020               EN              FT            Data Scientist   
3753       2020               EN              CT     Business Data Analyst   
3754       2021               SE              FT      Data Science Manager   

       salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
3750   412000             USD         412000                 US           100   
3751   151000             USD         151000                 US           100   
3752   105000             USD         105000                 US           100   
3753   100000             USD         100000                 US           100   
3754  7000000             INR          94665                 IN            50   

     company_location company_size  
3750               US            L  
3751               US            L  
3752               US            S  
3753               US            L  
3754               IN            L

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   work_year           3755 non-null   int64 
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64 
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64 
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64 
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB


In [ ]:
df.describe()

work_year        salary  salary_in_usd  remote_ratio
count  3755.000000  3.755000e+03    3755.000000   3755.000000
mean   2022.373635  1.906956e+05  137570.389880     46.271638
std       0.691448  6.716765e+05   63055.625278     48.589050
min    2020.000000  6.000000e+03    5132.000000      0.000000
25%    2022.000000  1.000000e+05   95000.000000      0.000000
50%    2022.000000  1.380000e+05  135000.000000      0.000000
75%    2023.000000  1.800000e+05  175000.000000    100.000000
max    2023.000000  3.040000e+07  450000.000000    100.000000

In [ ]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [ ]:
df.isna().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [ ]:
df1=df.drop(columns=['employment_type','salary','salary_currency','remote_ratio'],axis=1)
df1

work_year experience_level                 job_title  salary_in_usd  \
0          2023               SE  Principal Data Scientist          85847   
1          2023               MI               ML Engineer          30000   
2          2023               MI               ML Engineer          25500   
3          2023               SE            Data Scientist         175000   
4          2023               SE            Data Scientist         120000   
...         ...              ...                       ...            ...   
3750       2020               SE            Data Scientist         412000   
3751       2021               MI  Principal Data Scientist         151000   
3752       2020               EN            Data Scientist         105000   
3753       2020               EN     Business Data Analyst         100000   
3754       2021               SE      Data Science Manager          94665   

     employee_residence company_location company_size  
0                    ES               ES            L  
1                    US               US            S  
2                    US               US            S  
3                    CA               CA            M  
4                    CA               CA            M  
...                 ...              ...          ...  
3750                 US               US            L  
3751                 US               US            L  
3752                 US               US            S  
3753                 US               US            L  
3754                 IN               IN            L  

[3755 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1['experience_level']=le.fit_transform(df1['experience_level'])
df1['job_title']=le.fit_transform(df1['job_title'])
df1['employee_residence']=le.fit_transform(df1['employee_residence'])
df1['company_location']=le.fit_transform(df1['company_location'])
df1['company_size']=le.fit_transform(df1['company_location'])
df1

work_year  experience_level  job_title  salary_in_usd  \
0          2023                 3         84          85847   
1          2023                 2         66          30000   
2          2023                 2         66          25500   
3          2023                 3         47         175000   
4          2023                 3         47         120000   
...         ...               ...        ...            ...   
3750       2020                 3         47         412000   
3751       2021                 2         84         151000   
3752       2020                 0         47         105000   
3753       2020                 0         17         100000   
3754       2021                 3         45          94665   

      employee_residence  company_location  company_size  
0                     26                25            25  
1                     75                70            70  
2                     75                70            70  
3                     11                12            12  
4                     11                12            12  
...                  ...               ...           ...  
3750                  75                70            70  
3751                  75                70            70  
3752                  75                70            70  
3753                  75                70            70  
3754                  39                38            38  

[3755 rows x 7 columns]

In [ ]:
x=df1.drop(['salary_in_usd'],axis=1).values
x

array([[2023,    3,   84,   26,   25,   25],
       [2023,    2,   66,   75,   70,   70],
       [2023,    2,   66,   75,   70,   70],
       ...,
       [2020,    0,   47,   75,   70,   70],
       [2020,    0,   17,   75,   70,   70],
       [2021,    3,   45,   39,   38,   38]])

In [ ]:
y=df1['salary_in_usd'].values
y

array([ 85847,  30000,  25500, ..., 105000, 100000,  94665])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[2022,    3,   33,   75,   70,   70],
       [2022,    3,   25,   75,   70,   70],
       [2023,    2,   33,   75,   70,   70],
       ...,
       [2023,    1,   33,   75,   70,   70],
       [2021,    2,   89,   28,   27,   27],
       [2022,    2,   69,   28,   20,   20]])

In [ ]:
x_test


array([[2022,    3,   75,   11,   12,   12],
       [2023,    3,   25,   75,   70,   70],
       [2022,    3,   47,   75,   70,   70],
       ...,
       [2023,    3,   69,   75,   70,   70],
       [2020,    2,   64,    0,    0,    0],
       [2023,    3,   25,   75,   70,   70]])

In [ ]:
y_train

array([144000,  89200, 125000, ..., 310000,  62649,  84053])

In [ ]:
y_test

array([168000, 179975, 144000, ..., 163800, 115000, 153600])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
x_train

array([[0.66666667, 1.        , 0.35869565, 0.97402597, 0.98591549,
        0.98591549],
       [0.66666667, 1.        , 0.27173913, 0.97402597, 0.98591549,
        0.98591549],
       [1.        , 0.66666667, 0.35869565, 0.97402597, 0.98591549,
        0.98591549],
       ...,
       [1.        , 0.33333333, 0.35869565, 0.97402597, 0.98591549,
        0.98591549],
       [0.33333333, 0.66666667, 0.9673913 , 0.36363636, 0.38028169,
        0.38028169],
       [0.66666667, 0.66666667, 0.75      , 0.36363636, 0.28169014,
        0.28169014]])

In [ ]:
x_test

array([[0.66666667, 1.        , 0.82417582, 0.14473684, 0.17142857,
        0.17142857],
       [1.        , 1.        , 0.27472527, 0.98684211, 1.        ,
        1.        ],
       [0.66666667, 1.        , 0.51648352, 0.98684211, 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 0.75824176, 0.98684211, 1.        ,
        1.        ],
       [0.        , 0.66666667, 0.7032967 , 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.27472527, 0.98684211, 1.        ,
        1.        ]])

In [ ]:
#model creation using knn
from sklearn.neighbors import  KNeighborsClassifier
model1=KNeighborsClassifier(n_neighbors=5)
model1.fit(x_train,y_train)
y_pred1=model1.predict(x_test)
y_pred1

array([116100,  80000, 120000, ..., 171600,  12901,  80000])

In [ ]:
#performence evalution using knn

In [ ]:
#model creation using naive bayes algorithm
from sklearn.naive_bayes import GaussianNB
model2=GaussianNB()
model2.fit(x_train,y_train)
y_pred2=model2.predict(x_test)
y_pred2

array([183600,  94000, 183600, ..., 185000,  42000,  94000])

In [ ]:
#model creation using svm
from sklearn.svm import SVC
model3=SVC()
model3.fit(x_train,y_train)
y_pred3=model3.predict(x_test)
y_pred3


array([120000, 160000, 191475, ..., 150000,  88654, 160000])